---
- name: Download Confluent Platform tarball
  ansible.builtin.command:
    cmd: "wget http://packages.confluent.io/archive/6.1/confluent-community-6.1.0.tar.gz -O /opt/confluent-community-6.1.0.tar.gz"
  args:
    creates: /opt/confluent-community-6.1.0.tar.gz  # 이미 파일이 존재하면 다운로드 생략

- name: Extract Confluent tarball
  ansible.builtin.unarchive:
    src: /opt/confluent-community-6.1.0.tar.gz
    dest: /usr/local/
    remote_src: yes  # 원격 서버에 이미 있는 tar 파일 사용

- name: Create symbolic link for Confluent
  ansible.builtin.file:
    src: /usr/local/confluent-6.1.0
    dest: /usr/local/confluent
    state: link
    force: yes  # 기존 링크가 있을 경우 대체