---
- name: check if connector is already installed
  stat:
    path: /usr/local/kafka/connector
  register: connector_installed

- name: make dir kafka connector
  file:
    path: /usr/local/kafka/connector
    state: directory
    mode: '0755'
  when: not connector_installed.stat.exists

- name: download kafka connector from web
  get_url:
    url: https://github.com/Aiven-Open/opensearch-connector-for-apache-kafka/releases/download/v{{connector_opensearch_version}}/opensearch-connector-for-apache-kafka-{{connector_opensearch_version}}.zip
    dest: /opt/
    mode: '0600'
  when: not connector_installed.stat.exists

- name: unarchive kafka connector
  unarchive:
    src: /opt/opensearch-connector-for-apache-kafka-{{connector_opensearch_version}}.zip
    dest: /usr/local/kafka/connector
    remote_src: yes
  when: not connector_installed.stat.exists

- name: Download Avro Converter JAR
  get_url:
    url: https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/7.4.0/kafka-connect-avro-converter-7.4.0.jar
    dest: /usr/local/kafka/libs/kafka-connect-avro-converter-7.4.0.jar
    mode: '0644'
  when: not connector_installed.stat.exists

- name: Download schema-registry client JAR
  get_url:
    url: https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.4.0/kafka-schema-registry-client-7.4.0.jar
    dest: /usr/local/kafka/libs/kafka-schema-registry-client-7.4.0.jar
    mode: '0644'
  when: not connector_installed.stat.exists

- name: Download schema-serializer JAR
  get_url:
    url: https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.4.0/kafka-schema-serializer-7.4.0.jar
    dest: /usr/local/kafka/libs/kafka-schema-serializer-7.4.0.jar
    mode: '0644'
  when: not connector_installed.stat.exists

- name: Download guava JAR
  get_url:
    url: https://repo1.maven.org/maven2/com/google/guava/guava/30.1.1-jre/guava-30.1.1-jre.jar
    dest: /usr/local/kafka/libs/guava-30.1.1-jre.jar
    mode: '0644'
#  when: not connector_installed.stat.exists

- name: Download OpenSearch Kafka Connector
  get_url:
    url: https://github.com/Aiven-Open/opensearch-connector-for-apache-kafka/releases/download/v3.1.1/opensearch-connector-for-apache-kafka-3.1.1.tar
    dest: /usr/local/kafka/libs/opensearch-connector-for-apache-kafka-3.1.1.tar
    mode: '0644'
  when: not connector_installed.stat.exists

- name: Apply OpenSearch Kafka Connector
  ansible.builtin.unarchive:
    src: /usr/local/kafka/libs/opensearch-connector-for-apache-kafka-3.1.1.tar
    dest: /usr/local/kafka/libs/
    remote_src: yes
  when: not connector_installed.stat.exists

- name: copy kafka-connect conf file
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/kafka/config/{{ item }}"
    mode: '0644'
  with_items:
    - connect-distributed.properties
    - connect-opensearch-sink.properties
  vars:
    rest_host: "{{ hostvars[inventory_hostname]['hostname'] }}"
  notify:
    - restart kafka-connect server

- name: copy kafka kafka-connect in systemd
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
    backup: no
  with_items:
    - kafka-connect.service
  notify:
    - restart kafka-connect server
