---
- name: check if connector is already installed
  stat:
    path: /usr/local/kafka/connector
  register: connector_installed

- name: make dir kafka connector
  file:
    path: /usr/local/kafka/connector
    state: directory
    mode: '0755'
  when: not connector_installed.stat.exists

- name: download kafka connector from web
  get_url:
    url: https://github.com/Aiven-Open/opensearch-connector-for-apache-kafka/releases/download/v{{connector_opensearch_version}}/opensearch-connector-for-apache-kafka-{{connector_opensearch_version}}.zip
    dest: /opt/
    mode: '0600'
#  when: not connector_installed.stat.exists

- name: unarchive kafka connector
  unarchive:
    src: /opt/opensearch-connector-for-apache-kafka-{{connector_opensearch_version}}.zip
    dest: /usr/local
    remote_src: yes
#  when: not kafka_installed.stat.exists
#
- name: setup link kafka connector
  file:
    path: /usr/local/kafka/connector
    src: /usr/local/kafka/connector/opensearch-connector-for-apache-kafka-{{connector_opensearch_version}}
    state: link
    force: yes
#  when: not kafka_installed.stat.exists
#
#- name: copy kafka server conf files
#  template:
#    src: server.properties.j2
#    dest: /usr/local/kafka/config/server.properties
#    mode: '0644'
#    backup: no
#  notify:
#    - restart kafka server
#
#- name: copy kafka conf file
#  copy:
#    src: "{{ item }}"
#    dest: /usr/local/kafka/config/
#    mode: '0644'
#    backup: no
#  with_items:
#    - jmx
#    - connect-distributed.properties
#  notify:
#    - restart kafka server
#
#- name: copy kafka server in systemd
#  copy:
#    src: "{{ item }}"
#    dest: /etc/systemd/system/
#    owner: root
#    group: root
#    mode: '0644'
#    backup: no
#  with_items:
#    - kafka.service
#    - kafka-connect.service
#  notify:
#    - restart kafka server
