---
- name: check if zookeeper is already installed
  stat:
    path: /usr/local/zookeeper
  register: zookeeper_installed

- name: add the group zookeeper
  group:
    name: zookeeper
    state: present
  when: not zookeeper_installed.stat.exists

- name: add the user zookeeper
  user:
    name: zookeeper
    group: zookeeper
    state: present
  when: not zookeeper_installed.stat.exists

- name: make dir zookeeper
  file:
    path: "{{ dir_path }}"
    state: directory
    owner: zookeeper
    group: zookeeper
    mode: '0755'
  when: not zookeeper_installed.stat.exists

- name: download zookeeper from web
  get_url:
    url: "https://archive.apache.org/dist/zookeeper/{{ zookeeperversion }}/apache-{{ zookeeperversion }}-bin.tar.gz"
    dest: /opt/
    mode: '0600'
  when: not zookeeper_installed.stat.exists

- name: unarchive zookeeper
  unarchive:
    src: "/opt/apache-{{ zookeeperversion }}-bin.tar.gz"
    dest: /usr/local
    owner: zookeeper
    group: zookeeper
    remote_src: yes
  when: not zookeeper_installed.stat.exists

- name: setup link zookeeper
  file:
    path: /usr/local/zookeeper
    src: "/usr/local/apache-{{ zookeeperversion }}-bin"
    owner: zookeeper
    group: zookeeper
    state: link
    force: yes
  when: not zookeeper_installed.stat.exists

- name: copy zookeeper server conf files
  template:
    src: zoo.cfg.j2
    dest: /usr/local/zookeeper/conf/zoo.cfg
    owner: zookeeper
    group: zookeeper
    mode: '0644'
    backup: no
  notify:
    - restart zookeeper server

- name: create myid
  shell: echo {{ myid }} > "{{ dir_path }}/myid"

- name: change file ownership, group and permissions
  file:
    path: "{{ dir_path }}/myid"
    owner: zookeeper
    group: zookeeper
    mode: '0644'

- name: copy zookeeper server in systemd
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify:
    - restart zookeeper server

- name: make sure a service is running
  systemd:
    state: started
    name: zookeeper
    enabled: yes
