---
- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul

- name: Install Java and Tools
  yum:
    name:
      - 'dstat'
      - 'java-{{ java_version }}-openjdk'
      - 'java-{{ java_version }}-openjdk-devel'
    state: latest

- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.hostname }}"
    state: present
  loop: "{{ hosts_entries }}"

- name: Verify SSH access to all servers
  shell: "ssh -o StrictHostKeyChecking=no ec2-user@{{ item.fqdn }} exit"
  loop: "{{ hosts_entries }}"
  environment:
    ANSIBLE_SSH_PRIVATE_KEY_FILE: /home/ec2-user/keypair.pem
  ignore_errors: true
