---
- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul

- name: Install Java and Tools
  yum:
    name:
      - 'dstat'
      - 'java-{{ java_version }}-openjdk'
      - 'java-{{ java_version }}-openjdk-devel'
    state: latest

- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }} {{ hostvars[item].hostname }}"
    state: present
  loop: "{{ groups[inventory_hostname_short.split('.')[0] ~ '_hosts'] }}"
  when: hostvars[item].ansible_host is defined and hostvars[item].hostname is defined