---
- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul

- name: Install Java and Tools
  dnf:
    name:
      - 'sysstat'
      - 'java-{{ java_version }}-amazon-corretto.x86_64'
      - 'java-{{ java_version }}-amazon-corretto-devel.x86_64'
    state: latest

- name: Change to project directory and pull latest changes
  shell: |
    cd /home/ec2-user/kafka_system_with_azar/
    git pull

- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }} {{ hostvars[item].hostname }}"
    state: present
  loop: "{{ groups[inventory_hostname_short.split('_')[0] ~ '_hosts'] }}"
  when: hostvars[item].ansible_host is defined and hostvars[item].hostname is defined