---
- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul

- name: install Java and tools
  yum:
    name:
      - 'dstat'
      - 'java-{{ java_version }}-openjdk'
      - 'java-{{ java_version }}-openjdk-devel'
    state: latest