---
- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul

- name: Install Java and Tools
  yum:
    name:
      - 'dstat'
      - 'java-{{ java_version }}-openjdk'
      - 'java-{{ java_version }}-openjdk-devel'
    state: latest

- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.hostname }}"
    state: present
  loop: "{{ hosts_entries }}"

- name: Ensure .ssh directory exists
  file:
    path: /home/ec2-user/.ssh
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0700'

- name: Generate SSH key pair if not exists
  command: ssh-keygen -t rsa -f /home/ec2-user/.ssh/id_rsa -q -N ""
  args:
    creates: /home/ec2-user/.ssh/id_rsa
  become_user: ec2-user

- name: Read the public key content
  shell: cat /home/ec2-user/.ssh/id_rsa.pub
  register: ssh_pub_key
  become_user: ec2-user

- name: Create authorized_keys file with the public key
  copy:
    content: "{{ ssh_pub_key.stdout }}\n"
    dest: /home/ec2-user/.ssh/authorized_keys
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Add additional key (optional)
  copy:
    src: /home/ec2-user/keypair.pem
    dest: /home/ec2-user/.ssh/keypair.pem
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Start ssh-agent and add the keypair (optional)
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/ec2-user/.ssh/keypair.pem
  become_user: ec2-user
  args:
    executable: /bin/bash

- name: Verify SSH access to all servers
  shell: "ssh -o StrictHostKeyChecking=no ec2-user@{{ item.fqdn }} exit"
  loop: "{{ hosts_entries }}"
  ignore_errors: true
