---
- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.hostname }}"
    state: present
  loop: "{{ hosts_entries }}"

- name: Start SSH agent
  shell: |
    eval "$(ssh-agent -s)"
    echo $SSH_AUTH_SOCK
  register: ssh_agent_output

- name: Extract SSH_AUTH_SOCK
  set_fact:
    ssh_auth_sock: "{{ ssh_agent_output.stdout_lines[-1] }}"

- name: Add keypair.pem to SSH agent
  shell: ssh-add /home/ec2-user/keypair.pem
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"
  args:
    executable: /bin/bash

- name: Verify SSH access to all servers
  shell: "ssh -o StrictHostKeyChecking=no ec2-user@{{ item.fqdn }} exit"
  loop: "{{ hosts_entries }}"
  ignore_errors: true

