kafkaversion: 2.6.0
brokerid: "{{ inventory_hostname | regex_search('(kafka_0[0-9]\\.com)') | regex_replace('\\.com', '') | regex_replace('^kafka_0', '') }}"
zookeeperinfo: "{{ inventory_hostname | regex_search('(zookeeper_0[0-9]\\.com)') | regex_replace('\\.com', '') | regex_replace('^zookeeper_0', '') }}"
dir_path: /data/kafka-logs