kafkaversion: 2.6.0
brokerid: "{{ inventory_hostname | regex_search('(kafka_0[0-9]\\.com)') | regex_replace('\\.com', '') | regex_replace('^kafka_0', '') }}"
zookeeperinfo: "{{ groups['zookeeper_hosts'] | map('regex_replace', '^([^:]+)$', '\\1:2181') | join(',') }}"
dir_path: /data/kafka-logs

schema_registry_version: 6.1.0
schema_registry_archive: 6.1

connector_opensearch_version: 3.1.1

opensearch_version: 2.9.0
opensearch_path: /usr/local/opensearch
opensearch_user: opensearch
opensearch_heap_size: 1g