zookeeperversion: zookeeper-3.5.9
myid: "{{ inventory_hostname | regex_search('(zookeeper_0[0-9]\\.com)') | regex_replace('\\.com', '') | regex_replace('^zookeeper_0', '') }}"
dir_path: /data/zookeeper