---
- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.hostname }}"
    state: present
  loop: "{{ hosts_entries }}"

- name: Verify SSH access to all servers
  shell: "sudo ssh -o StrictHostKeyChecking=no ec2-user@{{ item.fqdn }} exit"
  loop: "{{ hosts_entries }}"
  ignore_errors: true
